services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: lucas
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: lx
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  db-data:

networks:
  postgres_network:
